version: '3'
services:
  zookeeper1.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2181:2181"
    volumes:
      - "./data-a1:/data"
      - "./conf/:/opt/zookeeper/conf"
    environment:
     - "SERVER_JVMFLAGS=-Xmx512m"
  zookeeper2.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2182:2181"
    volumes:
      - "./data-a2:/data"
      - "./conf/:/opt/zookeeper/conf"
    environment:
     - "SERVER_JVMFLAGS=-Xmx512m"
  zookeeper3.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2183:2181"
    volumes:
      - "./data-a3:/data"
      - "./conf/:/opt/zookeeper/conf"
    environment:
     - "SERVER_JVMFLAGS=-Xmx512m"
  zookeeper4.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2184:2181"
    volumes:
      - "./data-a4:/data"
      - "./conf/:/opt/zookeeper/conf"
    environment:
     - "SERVER_JVMFLAGS=-Xmx512m"
  zookeeper5.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2185:2181"
    volumes:
      - "./data-a5:/data"
      - "./conf/:/opt/zookeeper/conf"
    environment:
     - "SERVER_JVMFLAGS=-Xmx512m"

