version: '3'
services:
  kafka1.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    volumes:
      - "./data-a1:/data"
      - "./conf-a1/:/etc/kafka/conf"
  kafka2.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    volumes:
      - "./data-a2:/data"
      - "./conf-a2/:/etc/kafka/conf"
  kafka3.a.local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    volumes:
      - "./data-a3:/data"
      - "./conf-a3/:/etc/kafka/conf"
